### ISSUE TITLE
You're only testing if cookies of a certain name exist

### ISSUE THREAD

**Issue by dondre** [MeRahulAhire/React-Node-Passwordless-Auth#1]
https://github.com/MeRahulAhire/React-Node-Passwordless-Auth/blob/3138a3c82404c2a78aaf92331a2eebf1d32a6b7f/client/src/auth.js#L17

What's to prevent someone from opening a console window and creating any cookie with the required names?

**Comment by MeRahulAhire** [comment]
Hi @dondre sorry for late response as I didn't noticed it. By the way In this project I haven't used error validation which ideally in real world you should do it. talking about cookies there are two types of cookies that I've used one being [httpOnly](https://www.youtube.com/watch?v=a5Krfkfl9MM) and other normal but for your use cases you can modify it according to your needs. If anyone tampers with cookies and if we get the error `invalid Tokens` on server we can make user logout forcefully to ensure security by redirecting it to `/logout` route
